/* Generated by scriptc from E:/AI-workspace/scriptc/runtime-lab/hello.ts. Do not edit. */
#include "scr_runtime.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

static struct { size_t rc; size_t len; size_t cap; char data[7]; } sc_lit_0 =
    { SIZE_MAX, 6, 6, "hello " };
static struct { size_t rc; size_t len; size_t cap; char data[22]; } sc_lit_1 =
    { SIZE_MAX, 21, 21, " from scriptc runtime" };
static struct { size_t rc; size_t len; size_t cap; char data[5]; } sc_lit_2 =
    { SIZE_MAX, 4, 4, "rust" };

static bool sc_g_e__x25_loaded; /* %loaded */

static ScrStr * sc_f_greet(ScrStr *sc_l_name_0);
static void sc_f__x25_init_0(void);
static void sc_f__x25_main(void);

static ScrStr * sc_f_greet(ScrStr *sc_l_name_0) { /* E:/AI-workspace/scriptc/runtime-lab/hello.ts:1 */
  ScrStr *sc_t0 = scr_str_retain((ScrStr *)&sc_lit_0);
  ScrStr *sc_t1 = scr_str_retain(sc_l_name_0);
  ScrStr *sc_t2 = scr_str_concat(sc_t0, sc_t1);
  ScrStr *sc_t3 = scr_str_retain((ScrStr *)&sc_lit_1);
  ScrStr *sc_t4 = scr_str_concat(sc_t2, sc_t3);
  scr_str_release(sc_t0);
  scr_str_release(sc_t1);
  scr_str_release(sc_t2);
  scr_str_release(sc_t3);
  scr_str_release(sc_l_name_0);
  return sc_t4; /* E:/AI-workspace/scriptc/runtime-lab/hello.ts:2 */
}

static void sc_f__x25_init_0(void) { /* E:/AI-workspace/scriptc/runtime-lab/hello.ts:1 */
  bool sc_t0 = sc_g_e__x25_loaded;
  if (sc_t0) {
    return; /* E:/AI-workspace/scriptc/runtime-lab/hello.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_e__x25_loaded = sc_t1; /* E:/AI-workspace/scriptc/runtime-lab/hello.ts:1 */
  ScrStr *sc_t2 = scr_str_retain((ScrStr *)&sc_lit_2);
  ScrStr *sc_t3 = sc_f_greet(sc_t2);
  ScrLogArg sc_t4[1];
  sc_t4[0].tag = SCR_ARG_STR; sc_t4[0].v.s = sc_t3;
  scr_console_log(1, sc_t4); /* E:/AI-workspace/scriptc/runtime-lab/hello.ts:4 */
  scr_str_release(sc_t3);
}

static void sc_f__x25_main(void) { /* E:/AI-workspace/scriptc/runtime-lab/hello.ts:1 */
  sc_f__x25_init_0(); /* E:/AI-workspace/scriptc/runtime-lab/hello.ts:1 */
}

int main(int argc, char **argv) {
  scr_init();
  scr_error_vts[0].pre = 0; scr_error_vts[0].post = 4; /* Error */
  scr_error_vts[1].pre = 1; scr_error_vts[1].post = 1; /* TypeError */
  scr_error_vts[2].pre = 2; scr_error_vts[2].post = 2; /* RangeError */
  scr_error_vts[3].pre = 3; scr_error_vts[3].post = 3; /* SyntaxError */
  scr_error_vts[4].pre = 4; scr_error_vts[4].post = 4; /* DOMException */
  scr_lib_init(argc, argv);
  sc_f__x25_main();
  /* no refcounted globals */
  return 0;
}
