/* Generated by scriptc from E:/AI-workspace/scriptc/runtime-lab/netchild.ts. Do not edit. */
#include "scr_runtime.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

static struct { size_t rc; size_t len; size_t cap; char data[4]; } sc_lit_0 =
    { SIZE_MAX, 3, 3, "cmd" };
static struct { size_t rc; size_t len; size_t cap; char data[3]; } sc_lit_1 =
    { SIZE_MAX, 2, 2, "/c" };
static struct { size_t rc; size_t len; size_t cap; char data[5]; } sc_lit_2 =
    { SIZE_MAX, 4, 4, "echo" };
static struct { size_t rc; size_t len; size_t cap; char data[9]; } sc_lit_3 =
    { SIZE_MAX, 8, 8, "child-ok" };
static struct { size_t rc; size_t len; size_t cap; char data[14]; } sc_lit_4 =
    { SIZE_MAX, 13, 13, "child.status=" };
static struct { size_t rc; size_t len; size_t cap; char data[5]; } sc_lit_5 =
    { SIZE_MAX, 4, 4, "null" };
static struct { size_t rc; size_t len; size_t cap; char data[14]; } sc_lit_6 =
    { SIZE_MAX, 13, 13, "child.stdout=" };
static struct { size_t rc; size_t len; size_t cap; char data[12]; } sc_lit_7 =
    { SIZE_MAX, 11, 11, "server-got=" };
static struct { size_t rc; size_t len; size_t cap; char data[5]; } sc_lit_8 =
    { SIZE_MAX, 4, 4, "utf8" };
static struct { size_t rc; size_t len; size_t cap; char data[5]; } sc_lit_9 =
    { SIZE_MAX, 4, 4, "pong" };
static struct { size_t rc; size_t len; size_t cap; char data[15]; } sc_lit_10 =
    { SIZE_MAX, 14, 14, "ReferenceError" };
static struct { size_t rc; size_t len; size_t cap; char data[45]; } sc_lit_11 =
    { SIZE_MAX, 44, 44, "Cannot access 'client' before initialization" };
static struct { size_t rc; size_t len; size_t cap; char data[5]; } sc_lit_12 =
    { SIZE_MAX, 4, 4, "ping" };
static struct { size_t rc; size_t len; size_t cap; char data[12]; } sc_lit_13 =
    { SIZE_MAX, 11, 11, "client-got=" };
static struct { size_t rc; size_t len; size_t cap; char data[10]; } sc_lit_14 =
    { SIZE_MAX, 9, 9, "127.0.0.1" };
static struct { size_t rc; size_t len; size_t cap; char data[12]; } sc_lit_15 =
    { SIZE_MAX, 11, 11, "timer-fired" };

static ScrUnion sc_unit_0 = { .rc = SIZE_MAX, .tag = 1 }; /* u1 unit arm */

typedef struct sc_rs_r0 sc_rs_r0; /* record r0 { address; family; port } */

struct sc_rs_r0 { /* record r0 { address; family; port } */
  size_t rc;
  ScrStr *sc_fld_address; /* address */
  ScrStr *sc_fld_family; /* family */
  double sc_fld_port; /* port */
};

static sc_rs_r0 *sc_rretain_r0(sc_rs_r0 *o);
static void sc_rrelease_r0(sc_rs_r0 *o);
static sc_rs_r0 *sc_rnew_r0(void);

static sc_rs_r0 *sc_rretain_r0(sc_rs_r0 *o) {
  if (o && o->rc != SIZE_MAX) o->rc++;
  return o;
}
static void sc_rrelease_r0(sc_rs_r0 *o) {
  if (!o || o->rc == SIZE_MAX) return;
  if (--o->rc == 0) {
    if (o->sc_fld_address) scr_str_release(o->sc_fld_address);
    if (o->sc_fld_family) scr_str_release(o->sc_fld_family);
    scr_obj_free_note();
    free(o);
  }
}
static sc_rs_r0 *sc_rnew_r0(void) {
  sc_rs_r0 *o = calloc(1, sizeof *o);
  if (!o) { scr_trap("scriptc: out of memory\n"); }
  o->rc = 1;
  scr_obj_alloc_note();
  return o;
}
static void *sc_rretain_r0_v(void *o) { return sc_rretain_r0((sc_rs_r0 *)o); }
static void sc_rrelease_r0_v(void *o) { sc_rrelease_r0((sc_rs_r0 *)o); }

static ScrSpawnRes *sc_g_e_child; /* child */
static bool sc_g_e__x25_loaded; /* %loaded */

static void sc_f__x25_init_0(void);
static void sc_f__x25_main(void);
static void sc_f__x25_fn2(ScrClosure *sc_env, ScrBytes *sc_l_chunk_0);
static void sc_f__x25_fn1(ScrClosure *sc_env, ScrNetSocket *sc_p_socket_0);
static void sc_f__x25_fn4(ScrClosure *sc_env);
static void sc_f__x25_fn5(ScrClosure *sc_env, ScrBytes *sc_l_chunk_0);
static void sc_f__x25_fn3(ScrClosure *sc_env);
static void sc_f__x25_fn0(ScrClosure *sc_env);

static ScrStr *sc_us_0(ScrUnion *v); /* ToString u1 */

static ScrStr *sc_us_0(ScrUnion *v) { /* ToString u1 */
  switch (v->tag) {
  case 0: return scr_f64_to_scrstr(scr_union_get_f64(v));
  case 1: return scr_str_retain((ScrStr *)&sc_lit_5);
  default: scr_trap("scriptc: internal error: invalid union tag\n");
  }
}


static void sc_f__x25_init_0(void) { /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:1 */
  bool sc_t0 = sc_g_e__x25_loaded;
  if (sc_t0) {
    return; /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:1 */
  }
  bool sc_t1 = true;
  sc_g_e__x25_loaded = sc_t1; /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:1 */
  ScrStr *sc_t2 = scr_str_retain((ScrStr *)&sc_lit_0);
  ScrArr *sc_t3 = scr_arr_new(SCR_ELEM_STR, 3);
  ScrStr *sc_t4 = scr_str_retain((ScrStr *)&sc_lit_1);
  scr_arr_push_ref(sc_t3, sc_t4);
  ScrStr *sc_t5 = scr_str_retain((ScrStr *)&sc_lit_2);
  scr_arr_push_ref(sc_t3, sc_t5);
  ScrStr *sc_t6 = scr_str_retain((ScrStr *)&sc_lit_3);
  scr_arr_push_ref(sc_t3, sc_t6);
  ScrSpawnRes *sc_t7 = scr_spawn_sync(sc_t2, sc_t3);
  scr_spawn_res_release(sc_g_e_child);
  sc_g_e_child = sc_t7; /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:8 */
  scr_str_release(sc_t2);
  scr_arr_release(sc_t3);
  ScrStr *sc_t8 = scr_str_retain((ScrStr *)&sc_lit_4);
  ScrSpawnRes *sc_t9 = scr_spawn_res_retain(sc_g_e_child);
  ScrUnion *sc_t10 = scr_spawn_res_has_status(sc_t9) ? scr_union_new_f64(0, scr_spawn_res_status(sc_t9)) : (ScrUnion *)&sc_unit_0;
  ScrStr *sc_t11 = sc_us_0(sc_t10);
  ScrStr *sc_t12 = scr_str_concat(sc_t8, sc_t11);
  ScrLogArg sc_t13[1];
  sc_t13[0].tag = SCR_ARG_STR; sc_t13[0].v.s = sc_t12;
  scr_console_log(1, sc_t13); /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:9 */
  scr_str_release(sc_t8);
  scr_spawn_res_release(sc_t9);
  scr_union_release(sc_t10);
  scr_str_release(sc_t11);
  scr_str_release(sc_t12);
  ScrStr *sc_t14 = scr_str_retain((ScrStr *)&sc_lit_6);
  ScrSpawnRes *sc_t15 = scr_spawn_res_retain(sc_g_e_child);
  ScrStr *sc_t16 = scr_spawn_res_stdout(sc_t15);
  ScrStr *sc_t17 = scr_str_trim(sc_t16);
  ScrStr *sc_t18 = scr_str_concat(sc_t14, sc_t17);
  ScrLogArg sc_t19[1];
  sc_t19[0].tag = SCR_ARG_STR; sc_t19[0].v.s = sc_t18;
  scr_console_log(1, sc_t19); /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:10 */
  scr_str_release(sc_t14);
  scr_spawn_res_release(sc_t15);
  scr_str_release(sc_t16);
  scr_str_release(sc_t17);
  scr_str_release(sc_t18);
  ScrClosure *sc_t20 = scr_closure_new((void *)&sc_f__x25_fn0, 0);
  double sc_t21 = 10.0;
  scr_set_timeout(sc_t20, sc_t21); /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:13 */
}

static void sc_f__x25_main(void) { /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:1 */
  sc_f__x25_init_0(); /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:1 */
}

static void sc_f__x25_fn2(ScrClosure *sc_env, ScrBytes *sc_l_chunk_0) { /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:18 */
  ScrBox *sc_l_socket_0 = sc_env->caps[0]; /* captured socket */
  ScrStr *sc_t0 = scr_str_retain((ScrStr *)&sc_lit_7);
  ScrBytes *sc_t1 = scr_bytes_retain(sc_l_chunk_0);
  ScrStr *sc_t2 = scr_str_retain((ScrStr *)&sc_lit_8);
  ScrStr *sc_t3 = scr_bytes_to_str(sc_t1, sc_t2);
  ScrStr *sc_t4 = scr_str_trim(sc_t3);
  ScrStr *sc_t5 = scr_str_concat(sc_t0, sc_t4);
  ScrLogArg sc_t6[1];
  sc_t6[0].tag = SCR_ARG_STR; sc_t6[0].v.s = sc_t5;
  scr_console_log(1, sc_t6); /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:19 */
  scr_str_release(sc_t0);
  scr_bytes_release(sc_t1);
  scr_str_release(sc_t2);
  scr_str_release(sc_t3);
  scr_str_release(sc_t4);
  scr_str_release(sc_t5);
  ScrNetSocket *sc_t7 = (ScrNetSocket *)scr_box_get_ref(sc_l_socket_0);
  ScrStr *sc_t8 = scr_str_retain((ScrStr *)&sc_lit_9);
  scr_net_sock_write_str(sc_t7, sc_t8); /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:20 */
  scr_net_sock_release(sc_t7);
  scr_str_release(sc_t8);
  ScrNetSocket *sc_t9 = (ScrNetSocket *)scr_box_get_ref(sc_l_socket_0);
  scr_net_sock_end(sc_t9); /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:21 */
  scr_net_sock_release(sc_t9);
  scr_bytes_release(sc_l_chunk_0);
}

static void sc_f__x25_fn1(ScrClosure *sc_env, ScrNetSocket *sc_p_socket_0) { /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:17 */
  ScrBox *sc_l_socket_0 = scr_box_new_obj(&scr_net_sock_retain_v, &scr_net_sock_release_v, NULL); /* socket (boxed param) */
  scr_box_set_ref(sc_l_socket_0, sc_p_socket_0);
  ScrNetSocket *sc_t0 = (ScrNetSocket *)scr_box_get_ref(sc_l_socket_0);
  ScrClosure *sc_t1 = scr_closure_new((void *)&sc_f__x25_fn2, 1);
  sc_t1->caps[0] = scr_box_retain(sc_l_socket_0);
  bool sc_t2 = false;
  scr_net_sock_on_data(sc_t0, sc_t1, &scr_net_data_thunk_bytes, sc_t2); /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:18 */
  scr_net_sock_release(sc_t0);
  scr_box_release(sc_l_socket_0);
}

static void sc_f__x25_fn4(ScrClosure *sc_env) { /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:27 */
  ScrBox *sc_l_client_0 = sc_env->caps[0]; /* captured client */
  if (sc_l_client_0->slot == 0) { /* TDZ: read before initialization */
    scr_throw_error_named((ScrStr *)&sc_lit_10, (ScrStr *)&sc_lit_11);
    return;
  }
  ScrNetSocket *sc_t0 = (ScrNetSocket *)scr_box_get_ref(sc_l_client_0);
  ScrStr *sc_t1 = scr_str_retain((ScrStr *)&sc_lit_12);
  scr_net_sock_write_str(sc_t0, sc_t1); /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:28 */
  scr_net_sock_release(sc_t0);
  scr_str_release(sc_t1);
}

static void sc_f__x25_fn5(ScrClosure *sc_env, ScrBytes *sc_l_chunk_0) { /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:30 */
  ScrBox *sc_l_client_0 = sc_env->caps[0]; /* captured client */
  ScrBox *sc_l_server_0 = sc_env->caps[1]; /* captured server */
  ScrStr *sc_t0 = scr_str_retain((ScrStr *)&sc_lit_13);
  ScrBytes *sc_t1 = scr_bytes_retain(sc_l_chunk_0);
  ScrStr *sc_t2 = scr_str_retain((ScrStr *)&sc_lit_8);
  ScrStr *sc_t3 = scr_bytes_to_str(sc_t1, sc_t2);
  ScrStr *sc_t4 = scr_str_trim(sc_t3);
  ScrStr *sc_t5 = scr_str_concat(sc_t0, sc_t4);
  ScrLogArg sc_t6[1];
  sc_t6[0].tag = SCR_ARG_STR; sc_t6[0].v.s = sc_t5;
  scr_console_log(1, sc_t6); /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:31 */
  scr_str_release(sc_t0);
  scr_bytes_release(sc_t1);
  scr_str_release(sc_t2);
  scr_str_release(sc_t3);
  scr_str_release(sc_t4);
  scr_str_release(sc_t5);
  if (sc_l_client_0->slot == 0) { /* TDZ: read before initialization */
    scr_throw_error_named((ScrStr *)&sc_lit_10, (ScrStr *)&sc_lit_11);
    scr_bytes_release(sc_l_chunk_0);
    return;
  }
  ScrNetSocket *sc_t7 = (ScrNetSocket *)scr_box_get_ref(sc_l_client_0);
  scr_net_sock_end(sc_t7); /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:32 */
  scr_net_sock_release(sc_t7);
  ScrNetServer *sc_t8 = (ScrNetServer *)scr_box_get_ref(sc_l_server_0);
  scr_net_server_close(sc_t8, NULL); /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:33 */
  scr_net_server_release(sc_t8);
  scr_bytes_release(sc_l_chunk_0);
}

static void sc_f__x25_fn3(ScrClosure *sc_env) { /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:24 */
  ScrBox *sc_l_server_0 = sc_env->caps[0]; /* captured server */
  sc_rs_r0 *sc_l_addr_0 = NULL; /* addr */
  double sc_l_port_0; /* port */
  ScrBox *sc_l_client_0 = NULL; /* client (boxed) */
  ScrNetServer *sc_t0 = (ScrNetServer *)scr_box_get_ref(sc_l_server_0);
  ScrStr *sc_t1 = scr_net_server_addr_ip(sc_t0);
  sc_rs_r0 *sc_t2 = sc_rnew_r0();
  sc_t2->sc_fld_address = sc_t1;
  sc_t2->sc_fld_family = scr_net_server_addr_family(sc_t0);
  sc_t2->sc_fld_port = scr_net_server_port(sc_t0);
  sc_l_addr_0 = sc_t2; /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:25 */
  scr_net_server_release(sc_t0);
  sc_rs_r0 *sc_t3 = sc_rretain_r0(sc_l_addr_0);
  double sc_t4 = sc_t3->sc_fld_port;
  sc_l_port_0 = sc_t4; /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:26 */
  sc_rrelease_r0(sc_t3);
  sc_l_client_0 = scr_box_new_obj(&scr_net_sock_retain_v, &scr_net_sock_release_v, NULL); /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:27 */ /* let client; */
  double sc_t5 = sc_l_port_0;
  ScrStr *sc_t6 = scr_str_retain((ScrStr *)&sc_lit_14);
  ScrClosure *sc_t7 = scr_closure_new((void *)&sc_f__x25_fn4, 1);
  sc_t7->caps[0] = scr_box_retain(sc_l_client_0);
  ScrNetSocket *sc_t8 = scr_net_connect(sc_t5, sc_t6, sc_t7);
  scr_box_set_ref(sc_l_client_0, sc_t8); /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:27 */
  scr_str_release(sc_t6);
  if (sc_l_client_0->slot == 0) { /* TDZ: read before initialization */
    scr_throw_error_named((ScrStr *)&sc_lit_10, (ScrStr *)&sc_lit_11);
    sc_rrelease_r0(sc_l_addr_0);
    scr_box_release(sc_l_client_0);
    return;
  }
  ScrNetSocket *sc_t9 = (ScrNetSocket *)scr_box_get_ref(sc_l_client_0);
  ScrClosure *sc_t10 = scr_closure_new((void *)&sc_f__x25_fn5, 2);
  sc_t10->caps[0] = scr_box_retain(sc_l_client_0);
  sc_t10->caps[1] = scr_box_retain(sc_l_server_0);
  bool sc_t11 = false;
  scr_net_sock_on_data(sc_t9, sc_t10, &scr_net_data_thunk_bytes, sc_t11); /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:30 */
  scr_net_sock_release(sc_t9);
  sc_rrelease_r0(sc_l_addr_0);
  scr_box_release(sc_l_client_0);
}

static void sc_f__x25_fn0(ScrClosure *sc_env) { /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:13 */
  ScrBox *sc_l_server_0 = NULL; /* server (boxed) */
  ScrStr *sc_t0 = scr_str_retain((ScrStr *)&sc_lit_15);
  ScrLogArg sc_t1[1];
  sc_t1[0].tag = SCR_ARG_STR; sc_t1[0].v.s = sc_t0;
  scr_console_log(1, sc_t1); /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:14 */
  scr_str_release(sc_t0);
  sc_l_server_0 = scr_box_new_obj(&scr_net_server_retain_v, &scr_net_server_release_v, NULL); /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:17 */
  ScrClosure *sc_t2 = scr_closure_new((void *)&sc_f__x25_fn1, 0);
  ScrNetServer *sc_t3 = scr_net_create_server(sc_t2, &scr_net_conn_thunk_sock);
  scr_box_set_ref(sc_l_server_0, sc_t3);
  ScrNetServer *sc_t4 = (ScrNetServer *)scr_box_get_ref(sc_l_server_0);
  double sc_t5 = 0.0;
  ScrClosure *sc_t6 = scr_closure_new((void *)&sc_f__x25_fn3, 1);
  sc_t6->caps[0] = scr_box_retain(sc_l_server_0);
  scr_net_listen(sc_t4, sc_t5, sc_t6); /* E:/AI-workspace/scriptc/runtime-lab/netchild.ts:24 */
  scr_net_server_release(sc_t4);
  scr_box_release(sc_l_server_0);
}

static void sc_release_globals(void) {
  scr_spawn_res_release(sc_g_e_child);
}

int main(int argc, char **argv) {
  scr_init();
  scr_error_vts[0].pre = 0; scr_error_vts[0].post = 4; /* Error */
  scr_error_vts[1].pre = 1; scr_error_vts[1].post = 1; /* TypeError */
  scr_error_vts[2].pre = 2; scr_error_vts[2].post = 2; /* RangeError */
  scr_error_vts[3].pre = 3; scr_error_vts[3].post = 3; /* SyntaxError */
  scr_error_vts[4].pre = 4; scr_error_vts[4].post = 4; /* DOMException */
  scr_lib_init(argc, argv);
  scr_net_install();
  scr_net_dyn_install();
  sc_f__x25_main();
  bool sc_loop_rejection = scr_loop_run(NULL);
  if (scr_exc_pending()) {
    scr_exc_print_uncaught();
    sc_release_globals(); return 1;
  }
  if (sc_loop_rejection) {
    scr_discard_unhandled_rejections();
    sc_release_globals(); return 1;
  }
  if (scr_report_unhandled_rejections()) {
    sc_release_globals(); return 1;
  }
  sc_release_globals();
  return 0;
}
